### PR TITLE
Add Firefox option

### PR DESCRIPTION
**Pull request by kamataryo**
Puppeteer team also provides Firefox API!
https://www.npmjs.com/package/puppeteer-firefox

This pull request enable option to use Firefox.

Though `puppeteer-firefox` is experimental, it working well.

### CODE REVIEW

**Review by miya0001 — APPROVED** [review]
Nice 👍

**Comment by miya0001** [comment]
@kamataryo Could you please fix conflict?

**Review by miya0001 — CHANGES_REQUESTED** [review]
Thanks! But please fix conflict. :)

**Comment by kamataryo** [comment]
@miya0001 Solved those conflict.
Unfortunately, the `setExtraHTTPHeaders` method has not been supported yet for the latest firefox-puppeteer. The `--accept-language` option is available only for the default `chrome` browser.

https://github.com/tilecloud/shootbot/pull/1/files#diff-2cce40143051e25f811b56c79d619bf5L46

**Comment by miya0001** [comment]
@kamataryo OK, thanks 👍

**Pull request merged**
